version: "3"
services:
  poetry-system:
    build: ../
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/poetry
      - ENV=DEVELOPMENT
  mongo:
    image: mongo
    ports:
    - "27017:27017"