openapi: 3.0.0
info:
  title: Login
  description: Route for logging into poetry
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Development server URL

paths:
  /api/login:
    post:
      summary: Logs in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful user login and JWT returned
        '400':
          description: Failed user login
