openapi: 3.0.0
info:
  title: Registration
  description: Route for registering for poetry
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Development server URL

paths:
  /api/registration:
    post:
      summary: Registers a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - email
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 20
                password:
                  type: string
                  minLength: 5
                  format: password
                email:
                  type: string
      responses:
        '200':
          description: Successful user registration
        '400':
          description: Invalid user parameters (username, password, or email)

  /api/registration/validate/{validationCode}:
    post:
      summary: Validates a user
      parameters:
        - in: path
          name: validationCode
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful user validation
        '400':
          description: Unsuccessful user validation
